name: Check for ScriptHookV Update

on:
  schedule:
    # This workflow is triggered every Friday at 08:00 UTC
    - cron: '0 8 * * 5'
  workflow_dispatch:

concurrency:
  group: check-update
  cancel-in-progress: true

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Download ScriptHookV download page
        run: |
          curl -o download_page.html https://www.dev-c.com/gtav/scripthookv/

      - name: Extract download link
        id: extract_link
        run: |
          DOWNLOAD_LINK=$(grep -i -oP '<a href="(.+?)" target="_blank">Download</a>' download_page.html | grep -oP 'https.+zip')
          echo "DOWNLOAD_LINK=$DOWNLOAD_LINK" >> $GITHUB_ENV

      - name: Download ScriptHookV
        run: |
            if [ -z "$DOWNLOAD_LINK" ]; then
              echo "No download link found."
              exit 1
            fi
            curl -L -o ScriptHookV.zip "$DOWNLOAD_LINK"

      - name: Extract ScriptHookV
        run: |
          if [ ! -f ScriptHookV.zip ]; then
            echo "ScriptHookV.zip not found."
            exit 1
          fi
          unzip -o ScriptHookV.zip -d ScriptHookV

      - name: Find ScriptHookV.dll
        id: find_dll
        run: |
          DLL_PATH=$(find ScriptHookV -name "ScriptHookV.dll" | head -n 1)
          if [ -z "$DLL_PATH" ]; then
            echo "ScriptHookV.dll not found."
            exit 1
          fi
          echo "DLL_PATH=$DLL_PATH" >> $GITHUB_ENV

      - name: Extract Legacy versions from ScriptHookV.dll
        id: extract_version
        run: |
          LEGACY_VERSIONS=$(strings -d "$DLL_PATH" | grep -oP '(VER_1_0.+)')
          if [ -z "$LEGACY_VERSIONS" ]; then
            echo "Version not found in ScriptHookV.dll."
            exit 1
          fi
          {
            echo 'LEGACY_VERSIONS<<EOF'
            echo $LEGACY_VERSIONS
            echo EOF
          } >> $GITHUB_ENV
          echo "Legacy versions found in ScriptHookV.dll:"
          echo "$LEGACY_VERSIONS"

      - name: Extract Enhanced versions from ScriptHookV.dll
        id: extract_enhanced_version
        run: |
          ENHANCED_VERSIONS=$(strings -d "$DLL_PATH" | grep -oP '(VER_EN_1_0.+)')
          if [ -z "$ENHANCED_VERSIONS" ]; then
            echo "Enhanced version not found in ScriptHookV.dll."
            exit 1
          fi
          {
            echo 'ENHANCED_VERSIONS<<EOF'
            echo $ENHANCED_VERSIONS
            echo EOF
          } >> $GITHUB_ENV
          echo "Enhanced version found in ScriptHookV.dll:"
          echo "$ENHANCED_VERSIONS"

      - name: Cleanup downloaded files
        run: |
          rm -f download_page.html ScriptHookV.zip
          rm -rf ScriptHookV

      - name: Update `version.zig` file
        run: |
          VERSION_FILE=$(find . -name "version.zig" | head -n 1)
          if [ -z "$VERSION_FILE" ]; then
            echo "version.zig file not found."
            exit 1
          fi
          rm -f "$VERSION_FILE"
          echo "pub const eGameVersion = enum(c_int) {" > "$VERSION_FILE"
            for VERSION in $(echo $LEGACY_VERSIONS | tr ' ' '\n'); do
            echo "    $VERSION," >> "$VERSION_FILE"
          done
          echo "" >> "$VERSION_FILE"
            for VERSION in $(echo $ENHANCED_VERSIONS | tr ' ' '\n'); do
            if [ "$VERSION" = "$(echo $ENHANCED_VERSIONS | tr ' ' '\n' | head -n 1)" ]; then
              echo "    $VERSION = 1001," >> "$VERSION_FILE"
            else
              echo "    $VERSION," >> "$VERSION_FILE"
            fi
            done
          echo "" >> "$VERSION_FILE"
          echo "    _," >> "$VERSION_FILE"
          echo "};" >> "$VERSION_FILE"
          zig fmt "$VERSION_FILE"
          echo "VERSION_FILE=$VERSION_FILE" >> $GITHUB_ENV

      - name: Create Pull Request if changes detected
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Update ScriptHookV versions"
          body: "This PR updates the ScriptHookV versions in `version.zig`."
          branch: "update-scripthookv-versions"
          commit-message: "Update ScriptHookV versions in version.zig"
          delete-branch: true
          signoff: true
